"""
Subdomain takeover checker — resolves DNS (CNAME) for a subdomain and probes
the resolved target for fingerprints of decommissioned cloud services that
leave a vulnerable dangling DNS record.

No external tool dependency — pure Python (uses socket + urllib only).
"""
from __future__ import annotations
import re
import socket
import ssl
import urllib.request
import urllib.error
from typing import List
from ..utils.logger import get_logger

log = get_logger()

# ---------------------------------------------------------------------------
# Service fingerprints.
# Each entry maps a CNAME suffix to a service name and a body/regex
# fingerprint that confirms the dangling record is claimable.
# ---------------------------------------------------------------------------
SERVICE_FINGERPRINTS = [
    {
        "service": "GitHub Pages",
        "cname_match": [".github.io", "github.io"],
        "body_signatures": [
            "There isn't a GitHub Pages site here",
            "For root URLs (like http://example.github.io/",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "Heroku",
        "cname_match": ["herokuapp.com", "herokuapp.com."],
        "body_signatures": [
            "No such app",
            "There's nothing here",
            "herokucdn.com/error-pages/no-such-app.html",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "AWS S3",
        "cname_match": ["s3.amazonaws.com", ".s3.amazonaws.com", "s3-website"],
        "body_signatures": [
            "The specified bucket does not exist",
            "NoSuchBucket",
            "The specified bucket is not valid",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "AWS CloudFront",
        "cname_match": ["cloudfront.net"],
        "body_signatures": [
            "Bad request",
            "ERROR: The request could not be satisfied",
            "Generated by cloudfront (CloudFront)",
        ],
        "http_status": [403, 404],
        "severity": "medium",
    },
    {
        "service": "Azure",
        "cname_match": [
            "azurewebsites.net", "cloudapp.net", "azureedge.net",
            "azurecontainer.io", "blob.core.windows.net",
        ],
        "body_signatures": [
            "404 Web Site not found",
            "The web site you have accessed is not available",
            "The resource you are looking for has been removed",
            "This Azure website could not be found",
            "The requested content does not exist",
            "ClientDisconnectException",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "DigitalOcean",
        "cname_match": ["ondigitalocean.app"],
        "body_signatures": [
            "The page you are looking for doesn't exist",
            "app could not be found",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "Tumblr",
        "cname_match": ["tumblr.com", ".tumblr.com"],
        "body_signatures": [
            "Whatever you were looking for doesn't currently exist at this address",
            "There's nothing here",
            "This domain isn't configured",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "Shopify",
        "cname_match": ["myshopify.com", ".myshopify.com"],
        "body_signatures": [
            "Sorry, this shop is currently unavailable",
            "The page you requested does not exist",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "Fastly",
        "cname_match": ["fastly.net", "fastly-ssl"],
        "body_signatures": [
            "Fastly error: unknown domain",
            "Please ensure that this domain has been added to a service",
            "domain not found",
        ],
        "http_status": [404, 503],
        "severity": "medium",
    },
    {
        "service": "Google Cloud Storage",
        "cname_match": ["c.storage.googleapis.com", "storage.googleapis.com"],
        "body_signatures": [
            "The specified bucket does not exist",
            "NoSuchBucket",
            "AccessDenied",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "Surge.sh",
        "cname_match": ["surge.sh", ".surge.sh"],
        "body_signatures": [
            "project not found",
            "This domain is not on Surge",
        ],
        "http_status": [404],
        "severity": "high",
    },
    {
        "service": "Pantheon",
        "cname_match": ["pantheonsite.io"],
        "body_signatures": [
            "The gods are wise",
            "Site not found",
            "This domain is not on Pantheon",
        ],
        "http_status": [404],
        "severity": "high",
    },
]


def check_takeover(subdomain: str) -> List[dict]:
    """
    Check a single subdomain for takeover potential.

    Steps:
      1. Resolve CNAME chain via socket.gethostbyname_ex + a CNAME lookup.
      2. If NXDOMAIN (dead DNS) → vulnerable.
      3. If CNAME points at a known service, fetch the resolved host and
         match the fingerprint.

    Returns a list of finding dicts.
    """
    findings: List[dict] = []
    subdomain = subdomain.strip().lower().rstrip(".")

    # 1. Resolve A record / check for NXDOMAIN.
    try:
        socket.gethostbyname(subdomain)
    except socket.gaierror as e:
        # NXDOMAIN (dead DNS). A dangling record pointing at a dead name
        # can often be claimed by registering that name.
        if "not found" in str(e).lower() or "name or service not known" in str(e).lower() \
                or "no data" in str(e).lower():
            # But first confirm there is a CNAME pointing somewhere — a dead
            # subdomain with no CNAME at all is just dead, not takeovable.
            cname = _resolve_cname(subdomain)
            if cname:
                findings.append({
                    "type": "subdomain_takeover",
                    "severity": "high",
                    "description": (
                        f"Subdomain '{subdomain}' has a CNAME to '{cname}' "
                        "but does not resolve (NXDOMAIN) — potential takeover "
                        "if '{cname}' can be registered"
                    ),
                    "url": subdomain,
                    "source": "subdomain_takeover",
                    "subdomain": subdomain,
                    "cname": cname,
                    "indicator": "nxdomain_with_cname",
                })
            else:
                findings.append({
                    "type": "subdomain_takeover",
                    "severity": "info",
                    "description": (
                        f"Subdomain '{subdomain}' does not resolve (NXDOMAIN) "
                        "and has no CNAME — dead subdomain, not takeovable"
                    ),
                    "url": subdomain,
                    "source": "subdomain_takeover",
                    "subdomain": subdomain,
                    "indicator": "nxdomain_no_cname",
                })
            return findings

    # 2. Resolve the CNAME chain.
    cname = _resolve_cname(subdomain)
    if not cname:
        # No CNAME and the host resolves — not a takeover candidate.
        return findings

    cname_low = cname.lower().rstrip(".")

    # 3. Match against known services.
    for svc in SERVICE_FINGERPRINTS:
        if not any(suf.lower().rstrip(".") in cname_low for suf in svc["cname_match"]):
            continue

        # Fetch the resolved host to confirm the fingerprint.
        target_url = f"http://{subdomain}/"
        result = _fetch(target_url)
        body = result["body"]
        status = result["status"]

        confirmed = False
        for sig in svc["body_signatures"]:
            if sig.lower() in body.lower():
                confirmed = True
                break
        # Also accept the documented HTTP status as a softer indicator.
        if status in svc.get("http_status", []) and not confirmed:
            confirmed = True  # weak confirmation; lower severity below.

        if confirmed:
            severity = svc["severity"] if body else "medium"
            findings.append({
                "type": "subdomain_takeover",
                "severity": severity,
                "description": (
                    f"Subdomain '{subdomain}' CNAME → '{cname}' points to "
                    f"decommissioned {svc['service']} service — takeover "
                    "likely if you can claim the resource"
                ),
                "url": target_url,
                "source": "subdomain_takeover",
                "subdomain": subdomain,
                "cname": cname,
                "service": svc["service"],
                "indicator": "fingerprint_match",
                "status": status,
            })
        else:
            findings.append({
                "type": "subdomain_takeover",
                "severity": "low",
                "description": (
                    f"Subdomain '{subdomain}' CNAME → '{cname}' matches "
                    f"{svc['service']} but the fingerprint did not confirm — "
                    "verify manually"
                ),
                "url": target_url,
                "source": "subdomain_takeover",
                "subdomain": subdomain,
                "cname": cname,
                "service": svc["service"],
                "indicator": "cname_match_no_fingerprint",
                "status": status,
            })
        return findings

    # CNAME points somewhere unknown — note for triage.
    findings.append({
        "type": "subdomain_takeover",
        "severity": "info",
        "description": (
            f"Subdomain '{subdomain}' has CNAME → '{cname}' to an unknown "
            "service — investigate manually for takeover potential"
        ),
        "url": f"http://{subdomain}/",
        "source": "subdomain_takeover",
        "subdomain": subdomain,
        "cname": cname,
        "indicator": "unknown_cname",
    })
    return findings


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _resolve_cname(subdomain: str) -> str:
    """
    Resolve the CNAME for a subdomain. socket doesn't expose CNAME directly,
    so we use gethostbyaddr-free approach: query with a manual resolver that
    inspects the getaddrinfo result.

    When a CNAME exists, socket.gethostbyname_ex returns the canonical name
    in the second element of its tuple.
    """
    try:
        # gethostbyname_ex returns (hostname, aliaslist, ipaddrlist).
        # For a CNAME, the primary 'hostname' is the canonical (resolved)
        # name, and 'aliaslist' contains the queried name.
        hostname, aliases, ips = socket.gethostbyname_ex(subdomain)
        if hostname and hostname.lower() != subdomain.lower():
            return hostname
        # Some resolvers put the CNAME target in the alias list.
        for alias in aliases:
            if alias.lower() != subdomain.lower():
                return alias
    except socket.gaierror:
        # NXDOMAIN — try a raw DNS CNAME query as a fallback (no external dep).
        return _manual_cname_query(subdomain)
    except Exception as e:
        log.debug(f"subdomain_takeover: CNAME resolution error for {subdomain}: {e}")
    return ""


def _manual_cname_query(subdomain: str) -> str:
    """
    Last-resort raw DNS query for CNAME records over UDP/53 using the public
    resolver 8.8.8.8. Pure stdlib — no dnspython.

    Returns the CNAME target as a string, or "" on failure.
    """
    try:
        # Build a minimal DNS query for type CNAME (5), class IN (1).
        transaction_id = b"\x12\x34"
        flags = b"\x01\x00"  # standard query, recursion desired
        qdcount = b"\x00\x01"
        ancount = b"\x00\x00"
        nscount = b"\x00\x00"
        arcount = b"\x00\x00"
        header = transaction_id + flags + qdcount + ancount + nscount + arcount

        # Encode the name as length-prefixed labels.
        question = b""
        for label in subdomain.split("."):
            encoded = label.encode("ascii")
            question += bytes([len(encoded)]) + encoded
        question += b"\x00"
        question += b"\x00\x05"  # type CNAME
        question += b"\x00\x01"  # class IN

        packet = header + question

        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(4)
        sock.sendto(packet, ("8.8.8.8", 53))
        data, _ = sock.recvfrom(1024)
        sock.close()

        # Parse the response. Skip header (12 bytes) + question section.
        # Then parse answer records looking for type CNAME (5).
        offset = 12
        # Skip question section (name + type(2) + class(2)).
        offset = _skip_name(data, offset)
        offset += 4  # type + class

        ancount = int.from_bytes(data[6:8], "big")
        for _ in range(ancount):
            offset = _skip_name(data, offset)
            rtype = int.from_bytes(data[offset:offset + 2], "big")
            offset += 2
            rclass = int.from_bytes(data[offset:offset + 2], "big")
            offset += 2
            ttl = int.from_bytes(data[offset:offset + 4], "big")
            offset += 4
            rdlength = int.from_bytes(data[offset:offset + 2], "big")
            offset += 2
            rdata = data[offset:offset + rdlength]
            offset += rdlength
            if rtype == 5:  # CNAME
                # Decode the domain name in rdata (with compression).
                cname = _decode_name(data, offset - rdlength)
                return cname.rstrip(".")
        return ""
    except Exception as e:
        log.debug(f"subdomain_takeover: manual CNAME query failed for {subdomain}: {e}")
        return ""


def _skip_name(data: bytes, offset: int) -> int:
    """Skip a DNS name (label sequence) in `data` starting at `offset`."""
    while offset < len(data):
        length = data[offset]
        if length == 0:
            return offset + 1
        if (length & 0xC0) == 0xC0:  # compression pointer
            return offset + 2
        offset += length + 1
    return offset


def _decode_name(data: bytes, offset: int) -> str:
    """Decode a DNS name (handling compression pointers) starting at offset."""
    labels = []
    jumped = False
    original_offset = offset
    while offset < len(data):
        length = data[offset]
        if length == 0:
            break
        if (length & 0xC0) == 0xC0:
            pointer = ((length & 0x3F) << 8) | data[offset + 1]
            if not jumped:
                original_offset = offset + 2
            offset = pointer
            jumped = True
            continue
        offset += 1
        labels.append(data[offset:offset + length].decode("ascii", errors="replace"))
        offset += length
    return ".".join(labels)


def _fetch(url: str, timeout: int = 10) -> dict:
    """Fetch a URL; return {'status', 'body'} (both empty/zero on failure)."""
    req = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                      "Chrome/120.0 Safari/537.36",
    })
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
            return {
                "status": resp.status,
                "body": resp.read().decode("utf-8", errors="replace")[:4096],
            }
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode("utf-8", errors="replace")[:4096]
        except Exception:
            pass
        return {"status": e.code, "body": body}
    except Exception:
        return {"status": 0, "body": ""}
